# This file is autogenerated, do not edit it directly, edit build/mktargets.py
# instead. To regenerate files, run build/mktargets.sh.

MODULE_SRCDIR=module
MODULE_CPP_SRCS=\
	$(MODULE_SRCDIR)/gmp-openh264.cpp\

MODULE_OBJS += $(MODULE_CPP_SRCS:.cpp=.$(OBJ))

OBJS += $(MODULE_OBJS)

$(MODULE_SRCDIR)/%.$(OBJ): $(MODULE_SRCDIR)/%.cpp
	$(QUIET_CXX)$(CXX) $(CFLAGS) $(CXXFLAGS) $(CXXSTD) $(INCLUDES) $(MODULE_CFLAGS) $(MODULE_INCLUDES) -c $(CXX_O) $<

