#include <gtest/gtest.h>
#include "codec_def.h"
#include "mc.h"
#include "cpu.h"
using namespace WelsDec;

#define DEF_MCCOPYTESTS    \
DEF_MCCOPYTEST (2, 2, 1)   \
DEF_MCCOPYTEST (2, 4, 1)   \
DEF_MCCOPYTEST (4, 2, 0)   \
DEF_MCCOPYTEST (4, 4, 0)   \
DEF_MCCOPYTEST (4, 8, 0)   \
DEF_MCCOPYTEST (8, 4, 0)   \
DEF_MCCOPYTEST (8, 8, 0)   \
DEF_MCCOPYTEST (16, 8, 0)  \
DEF_MCCOPYTEST (8, 16, 0)  \
DEF_MCCOPYTEST (16, 16, 0)

#define DEF_LUMA_MCTEST(a,b) \
DEF_LUMA_MCTEST_SUBCASE(a,b,4,4)  \
DEF_LUMA_MCTEST_SUBCASE(a,b,4,8)  \
DEF_LUMA_MCTEST_SUBCASE(a,b,8,4)  \
DEF_LUMA_MCTEST_SUBCASE(a,b,8,8)  \
DEF_LUMA_MCTEST_SUBCASE(a,b,16,8) \
DEF_LUMA_MCTEST_SUBCASE(a,b,8,16) \
DEF_LUMA_MCTEST_SUBCASE(a,b,16,16)

#define DEF_CHROMA_MCTEST(a,b) \
DEF_CHROMA_MCTEST_SUBCASE(a,b,2,2) \
DEF_CHROMA_MCTEST_SUBCASE(a,b,2,4) \
DEF_CHROMA_MCTEST_SUBCASE(a,b,4,2) \
DEF_CHROMA_MCTEST_SUBCASE(a,b,4,4) \
DEF_CHROMA_MCTEST_SUBCASE(a,b,4,8) \
DEF_CHROMA_MCTEST_SUBCASE(a,b,8,4) \
DEF_CHROMA_MCTEST_SUBCASE(a,b,8,8)

#include "mc_test_common.h"
