This file describes the interface of ISVCEncoder

.. contents::
    :local:
    :depth: 2


Methods(ISVCEncoder)
============================
<doxygen2rst class=ISVCEncoder> Class:ISVCEncoder </doxygen2rst>

Global functions
===========================
<doxygen2rst function=WelsCreateSVCEncoder> function:WelsCreateSVCEncoder </doxygen2rst>

<doxygen2rst function=WelsDestroySVCEncoder> function:WelsDestroySVCEncoder </doxygen2rst>