This page is about the example of encoder usage

.. contents::
    :local:
    :depth: 2


Encoder Usage Example-1
============================
<doxygen2rst page=EncoderUsageExample1> Encoder usage example 1 </doxygen2rst>

Encoder Usage Example-2
============================
<doxygen2rst page=EncoderUsageExample2> Encoder usage example 2 </doxygen2rst>

